#云编译公用核心
name: OWRT-CORE-N1

on:
  #公用核心标识
  workflow_call:
    inputs:
      OWRT_TARGET:
        required: true
        type: string
      OWRT_THEME:
        required: true
        type: string
      OWRT_NAME:
        required: true
        type: string
      OWRT_URL:
        required: true
        type: string
      OWRT_PW:
        required: true
        type: string
      OWRT_IP:
        required: true
        type: string
      OWRT_CFG:
        required: true
        type: string
      OWRT_BRANCH:
        required: true
        type: string
      OWRT_TYPE:
        required: true
        type: string
      OWRT_LINUX:
        required: true
        type: string
      OWRT_FILES:
        required: true
        type: string
      DIY_P1_SH:
        required: true
        type: string
      DIY_P2_SH:
        required: true
        type: string      
      TOWR_TAG:
        required: true
        type: string
        
env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  OWRT_TARGET: ${{inputs.OWRT_TARGET}}
  OWRT_THEME: ${{inputs.OWRT_THEME}}
  OWRT_NAME: ${{inputs.OWRT_NAME}}
  OWRT_URL: ${{inputs.OWRT_URL}}
  OWRT_PW: ${{inputs.OWRT_PW}}
  OWRT_IP: ${{inputs.OWRT_IP}}
  OWRT_CFG: ${{inputs.OWRT_CFG}}
  OWRT_BRANCH: ${{inputs.OWRT_BRANCH}}
  OWRT_TYPE: ${{inputs.OWRT_TYPE}}
  OWRT_LINUX: ${{inputs.OWRT_LINUX}}
  OWRT_FILES: ${{inputs.OWRT_FILES}}
  DIY_P1_SH: ${{inputs.DIY_P1_SH}}
  DIY_P2_SH: ${{inputs.DIY_P2_SH}}
  TOWR_TAG: ${{inputs.TOWR_TAG}}
  TZ: Asia/Shanghai
  #USE_CACHEWRTBUILD: true
  
jobs:
  owrt_core_N1:
    runs-on: ubuntu-latest
    steps:
    
      - name: 清理服务器空间(Ubuntu)
        uses: rmoyulong/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: true

          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          swap-storage: true
        
      - name: 项目检查
        uses: actions/checkout@main

      - name: 检查分配的服务器性能
        run: |
          echo "警告⚠"
          echo "分配的服务器性能有限，若选择的插件过多，务必注意CPU性能！"
          echo -e "已知CPU型号（降序）：7763，8370C，8272CL，8171M，E5-2673 \n"
          echo "--------------------------CPU信息--------------------------"
          echo "CPU物理数量：$(cat /proc/cpuinfo | grep "physical id" | sort | uniq | wc -l)"
          echo -e "CPU核心信息：$(cat /proc/cpuinfo | grep name | cut -f2 -d: | uniq -c) \n"
          echo "--------------------------内存信息--------------------------"
          echo "已安装内存详细信息："
          echo -e "$(sudo lshw -short -C memory | grep GiB) \n"
          echo "--------------------------硬盘信息--------------------------"
          echo "硬盘数量：$(ls /dev/sd* | grep -v [1-9] | wc -l)" && df -hT        
          
      - name: 初始化编译环境
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E apt-get -qq update --fix-missing
          sudo -E apt-get -qq full-upgrade
          sudo -E apt-get -qq install ack antlr3 aria2 asciidoc autoconf automake autopoint binutils bison build-essential \
          bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib \
          git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev \
          libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libreadline-dev libssl-dev libtool lrzsz \
          mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pip libpython3-dev qemu-utils \
          rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev dos2unix
          sudo -E apt-get -qq install time gn
          sudo -E apt-get -qq autoremove --purge
          sudo -E apt-get -qq clean
          sudo timedatectl set-timezone "$TZ"
          sudo mkdir -p /workdir
          sudo chown $USER:$GROUPS /workdir
          echo "status=success" >> ${GITHUB_OUTPUT}
          df -Th       

      - name: 初始化变量
        run: |
          export OWRT_DATE=$(TZ=UTC-8 date +"%y.%m.%d_%H.%M.%S")
          export OWRT_SOURCE=$(echo $OWRT_URL | cut -d '/' -f 5-)
          #export OWRT_TYPE="cortex-a53"

          echo "OWRT_SOURCE=$OWRT_SOURCE" >> $GITHUB_ENV
          echo "OWRT_TARGET=$OWRT_TARGET" >> $GITHUB_ENV
          echo "OWRT_DATE=$OWRT_DATE" >> $GITHUB_ENV
          echo "OWRT_TYPE=$OWRT_TYPE" >> $GITHUB_ENV
          echo "OWRT_PW=$OWRT_PW" >> $GITHUB_ENV
          echo "OWRT_IP=$OWRT_IP" >> $GITHUB_ENV
          echo "OWRT_LINUX=$OWRT_LINUX" >> $GITHUB_ENV
          echo "OWRT_FILES=$OWRT_FILES" >> $GITHUB_ENV
          echo "DIY_P1_SH=$DIY_P1_SH" >> $GITHUB_ENV
          echo "DIY_P2_SH=$DIY_P2_SH" >> $GITHUB_ENV
          echo "TOWR_TAG=$TOWR_TAG" >> $GITHUB_ENV

      - name: 检查脚本
        run: |
          cd ./N1
          
          sudo curl -L -o set_N1.sh http://mojialin.dynv6.net:9020/docker-N1.sh
          sudo dos2unix ./*.sh
          sudo chmod +x ./*.sh
          sudo dos2unix ./*.local
          sudo chmod +x ./*.local
        
      - name: 克隆源码库
        working-directory: /workdir
        run: |
          # Set up compilation source code
          if [[ "${{ inputs.OWRT_URL }}" == *"openwrt"* ]]; then
              REPO_URL="https://github.com/openwrt/openwrt"
              REPO_BRANCH="main"
              TAGS_NAME="official"
          elif [[ "${{ inputs.OWRT_URL }}" == *"lede"* ]]; then
              REPO_URL="https://github.com/coolsnowwolf/lede"
              REPO_BRANCH="master"
              TAGS_NAME="lede"
          elif [[ "${{ inputs.OWRT_URL }}" == *"immortalwrt"* ]]; then
              REPO_URL="https://github.com/immortalwrt/immortalwrt"
              REPO_BRANCH="master"
              TAGS_NAME="immortalwrt"
          else
              echo "Unknown source code repository."
              exit 1
          fi        
        
          df -hT $PWD
          git clone -q --single-branch --depth=1 --branch=${REPO_BRANCH} ${REPO_URL} openwrt
          #git clone $OWRT_URL -b $OWRT_BRANCH openwrt
          #git clone $OWRT_URL openwrt
          
          ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt

      - name: 检查docker环境
        working-directory: /workdir
        run: |
          export DOCKER_CLI_EXPERIMENTAL=enabled
          echo "docker buildx 版本"
          docker buildx version
          #echo "ls -l /proc/sys/fs/binfmt_misc"
          #ls -l /proc/sys/fs/binfmt_misc
          #echo "docker run --privileged --rm tonistiigi/binfmt --install all"
          #docker run --privileged --rm tonistiigi/binfmt --install all
          #echo "ls -l /proc/sys/fs/binfmt_misc"
          #ls -l /proc/sys/fs/binfmt_misc
          docker buildx create --use --name mybuilder
          docker buildx inspect mybuilder --bootstrap
          echo "docker buildx ls"
          docker buildx ls
 
      - name: 生成hub docker固件
        id: hubdocker
        run: |
          sudo curl -L -o N1/openwrt-armvirt-64-generic-rootfs.tar.gz "${OWRT_CFG}"
          
          cd ./N1
          #gzip openwrt-armvirt-onecloud-rootfs.tar
         
          sudo bash set_N1.sh "${TOWR_TAG}"
          #docker load < opt/imgs/docker-img-openwrt-oncloud-${TOWR_TAG}.gz
          
          #sudo docker tag mojialin/openwrt_onecloud mojialin/openwrt_onecloud:${TOWR_TAG}        
          #sudo docker push mojialin/openwrt_onecloud
          #sudo docker push mojialin/openwrt_onecloud:${TOWR_TAG} 

      - name: 清理Workflows
        uses: rmoyulong/delete-workflow-runs@main
        with:
          retain_days: 0
          keep_minimum_runs: 1
